window.candidatesData=[
  {
    "name": "林 則行",
    "age": "51",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "千代田区",
    "proportional_rank": "",
    "relation": "旧統一教会関連団体の会合に出席したほか、選挙活動で支援を受けていたことを東京都のアンケートで認めています。",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": ""
  },
  {
    "name": "内田 直之",
    "age": "61",
    "party": "無所属",
    "recommendation": "",
    "district": "千代田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "平 けいしょう",
    "age": "37",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "千代田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "やなぎさわ 誉之",
    "age": "41",
    "party": "再生の道",
    "recommendation": "",
    "district": "千代田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "木村 正明",
    "age": "70",
    "party": "日本共産党",
    "recommendation": "",
    "district": "千代田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "ナカジマ ケンジ",
    "age": "53",
    "party": "自治労と自治労連から国民を守る党",
    "recommendation": "",
    "district": "千代田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "天野 こころ",
    "age": "35",
    "party": "再生の道",
    "recommendation": "",
    "district": "中央区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "高橋 まきこ",
    "age": "47",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "中央区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "石島 ひでき",
    "age": "65",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "中央区",
    "proportional_rank": "",
    "relation": "統一教会関連団体の会合に「出席したことがある」と都のアンケートに回答",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": "30万円"
  },
  {
    "name": "愛 みちこ",
    "age": "62",
    "party": "社会民主党",
    "recommendation": "日本共産党/東京・生活者ネットワーク",
    "district": "中央区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "佐藤 ひろき",
    "age": "54",
    "party": "無所属",
    "recommendation": "",
    "district": "中央区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "金沢 一樹",
    "age": "36",
    "party": "無所属",
    "recommendation": "",
    "district": "港区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "加藤 なぎさ",
    "age": "45",
    "party": "無所属",
    "recommendation": "",
    "district": "港区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "宮崎 だいすけ",
    "age": "45",
    "party": "国民民主党",
    "recommendation": "",
    "district": "港区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "かんの 弘一",
    "age": "66",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "港区",
    "proportional_rank": "",
    "relation": "統一教会関連団体の会合に「出席したことがある」と都のアンケートに回答",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": ""
  },
  {
    "name": "山野井 つよし",
    "age": "46",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "港区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "吉野 じゅんこ",
    "age": "55",
    "party": "無所属",
    "recommendation": "",
    "district": "港区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "田島 みわ",
    "age": "61",
    "party": "無所属",
    "recommendation": "",
    "district": "港区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "古城 まさお",
    "age": "45",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "新宿区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "三雲 たかまさ",
    "age": "48",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "新宿区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "たいら 雄大",
    "age": "38",
    "party": "再生の道",
    "recommendation": "",
    "district": "新宿区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "宮本 せな",
    "age": "34",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "新宿区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "弘田 としやす",
    "age": "44",
    "party": "再生の道",
    "recommendation": "",
    "district": "新宿区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "大山 とも子",
    "age": "69",
    "party": "日本共産党",
    "recommendation": "",
    "district": "新宿区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "吉住 はるお",
    "age": "52",
    "party": "自由民主党",
    "recommendation": "",
    "district": "新宿区",
    "proportional_rank": "",
    "relation": "統一教会関連団体の会合に「出席したことがある」と都のアンケートに回答",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": "46万円"
  },
  {
    "name": "おくもと ゆり",
    "age": "48",
    "party": "国民民主党",
    "recommendation": "",
    "district": "新宿区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "増子 ひろき",
    "age": "65",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "文京区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "福手 ゆう子",
    "age": "48",
    "party": "日本共産党",
    "recommendation": "",
    "district": "文京区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "なかや 文孝",
    "age": "59",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "文京区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "保坂 まさひろ",
    "age": "51",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "台東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "中山 寛進",
    "age": "53",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "台東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "岩崎 あきら",
    "age": "71",
    "party": "再生の道",
    "recommendation": "",
    "district": "台東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "鈴木 純",
    "age": "43",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "台東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "坪田 こうすけ",
    "age": "35",
    "party": "再生の道",
    "recommendation": "",
    "district": "墨田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "加藤 まさゆき",
    "age": "60",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "墨田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "なりきよ りさこ",
    "age": "35",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "墨田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "藤崎 こうき",
    "age": "35",
    "party": "自由民主党",
    "recommendation": "",
    "district": "墨田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "伊藤 大気",
    "age": "46",
    "party": "日本共産党",
    "recommendation": "",
    "district": "墨田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "大つき かおり",
    "age": "58",
    "party": "日本共産党",
    "recommendation": "",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "高橋 たくみ",
    "age": "26",
    "party": "国民民主党",
    "recommendation": "",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "細田 いさむ",
    "age": "64",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "白戸 太朗",
    "age": "58",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "さんのへ あや",
    "age": "36",
    "party": "無所属",
    "recommendation": "",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "千葉 さきえ",
    "age": "45",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "やまざき 一輝",
    "age": "52",
    "party": "無所属",
    "recommendation": "",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "16万円"
  },
  {
    "name": "梅木 大輝",
    "age": "37",
    "party": "無所属",
    "recommendation": "",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "小林 ゆか",
    "age": "53",
    "party": "無所属",
    "recommendation": "",
    "district": "江東区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "白石 たみお",
    "age": "43",
    "party": "日本共産党",
    "recommendation": "",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "石田 しんご",
    "age": "46",
    "party": "国民民主党",
    "recommendation": "",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "岡本 ゆうじ",
    "age": "37",
    "party": "再生の道",
    "recommendation": "",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "ひがし ゆき",
    "age": "35",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "しのはら りか",
    "age": "35",
    "party": "無所属",
    "recommendation": "",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "伊藤 こういち",
    "age": "64",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "せりざわ 裕次郎",
    "age": "35",
    "party": "自由民主党",
    "recommendation": "",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "岡本 さとし",
    "age": "27",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "かわぐち めぐみ",
    "age": "52",
    "party": "無所属",
    "recommendation": "公明党",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "古田 真",
    "age": "78",
    "party": "土頭を働かし最高裁裁判官5人を弾劾する党身体から地頭へ人の増える会",
    "recommendation": "",
    "district": "品川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "加藤 あやこ",
    "age": "46",
    "party": "無所属",
    "recommendation": "",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "松尾 ゆうき",
    "age": "33",
    "party": "再生の道",
    "recommendation": "",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "山口 せいや",
    "age": "28",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "吉永",
    "age": "50",
    "party": "無所属",
    "recommendation": "",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "青木 英太",
    "age": "35",
    "party": "無所属",
    "recommendation": "",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "たぞえ 麻友",
    "age": "42",
    "party": "無所属",
    "recommendation": "",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "すどう 健太郎",
    "age": "55",
    "party": "健康長寿の党",
    "recommendation": "",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "西崎 つばさ",
    "age": "41",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "つちや すみこ",
    "age": "",
    "party": "無所属",
    "recommendation": "",
    "district": "目黒区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "福井 ゆうた",
    "age": "38",
    "party": "国民民主党",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "大和 ゆきお",
    "age": "47",
    "party": "無所属",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "もり 愛",
    "age": "48",
    "party": "無所属",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "かつまた さとし",
    "age": "62",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "みぞぐち 晃一",
    "age": "56",
    "party": "無所属",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "加藤 てつお",
    "age": "51",
    "party": "再生の道",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "おぎの 稔",
    "age": "39",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "鈴木 あきひろ",
    "age": "62",
    "party": "無所属",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "統一教会関連団体の会合に「出席したことがある」と都のアンケートで回答",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": "132万円"
  },
  {
    "name": "もがみ よしのり",
    "age": "49",
    "party": "参政党",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "山下 こういち",
    "age": "54",
    "party": "再生の道",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "玉川 ひでとし",
    "age": "56",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "松田 りゅうすけ",
    "age": "37",
    "party": "日本維新の会",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "ゆもと 良太郎",
    "age": "49",
    "party": "自由民主党",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "藤田 りょうこ",
    "age": "50",
    "party": "日本共産党",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "おけや まさと",
    "age": "29",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "原 忠信",
    "age": "73",
    "party": "区民ファーストの会",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "おち ひろゆき",
    "age": "51",
    "party": "自治労と自治労連から国民を守る党",
    "recommendation": "",
    "district": "大田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "小松",
    "age": "47",
    "party": "自由民主党",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "望月 まさのり",
    "age": "35",
    "party": "参政党",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "とりうみ あや",
    "age": "37",
    "party": "再生の道",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "坂本 まさし",
    "age": "54",
    "party": "国民民主党",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "くれ よしつぐ",
    "age": "53",
    "party": "再生の道",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "河村 建一",
    "age": "49",
    "party": "無所属",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "じんむら 浩平",
    "age": "41",
    "party": "れいわ新選組",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "たかく 則男",
    "age": "62",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "なかしま 里奈",
    "age": "37",
    "party": "国民民主党",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "高野 たかひろ",
    "age": "46",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "あべ 力也",
    "age": "62",
    "party": "",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "里吉 ゆみ",
    "age": "58",
    "party": "日本共産党",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "三宅 しげき",
    "age": "75",
    "party": "無所属",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "251万円"
  },
  {
    "name": "福島 りえこ",
    "age": "54",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "風間 ゆたか",
    "age": "52",
    "party": "立憲民主党",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "高岡 じゅん子",
    "age": "65",
    "party": "東京・生活者ネットワーク",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "加藤 陽三",
    "age": "41",
    "party": "無所属",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "平井 しげる",
    "age": "",
    "party": "自治労と自治労連から国民を守る党",
    "recommendation": "",
    "district": "世田谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "龍円 あいり",
    "age": "48",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "渋谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "中村 たけし",
    "age": "49",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "渋谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "中田 たかし",
    "age": "35",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "渋谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "はぎわら 崇",
    "age": "42",
    "party": "再生の道",
    "recommendation": "",
    "district": "渋谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "出村 浩司",
    "age": "55",
    "party": "無所属",
    "recommendation": "",
    "district": "渋谷区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "荒木 ちはる",
    "age": "43",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "中野区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "久保 りか",
    "age": "61",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "中野区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "いでい 良輔",
    "age": "51",
    "party": "自由民主党",
    "recommendation": "",
    "district": "中野区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "マエキタ ミヤコ",
    "age": "61",
    "party": "無所属",
    "recommendation": "",
    "district": "中野区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "西沢 けいた",
    "age": "45",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "中野区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "石倉 こうじろう",
    "age": "27",
    "party": "無所属",
    "recommendation": "",
    "district": "中野区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "奥本 かずき",
    "age": "41",
    "party": "再生の道",
    "recommendation": "",
    "district": "中野区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "海保 とくま",
    "age": "30",
    "party": "れいわ新選組",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "あかねがくぼ かよ子",
    "age": "49",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "増田 よしひこ",
    "age": "67",
    "party": "再生の道",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "松本 みつひろ",
    "age": "41",
    "party": "日本維新の会",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "国崎 たかし",
    "age": "43",
    "party": "国民民主党",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "まつば 多美子",
    "age": "62",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "青柳 みつや",
    "age": "36",
    "party": "再生の道",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "こすみ けんしろう",
    "age": "47",
    "party": "再生の道",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "関口 健太郎",
    "age": "33",
    "party": "立憲民主党",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "原田 あきら",
    "age": "49",
    "party": "日本共産党",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "小宮 あんり",
    "age": "49",
    "party": "無所属",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "250万円"
  },
  {
    "name": "早坂 よしひろ",
    "age": "56",
    "party": "自由民主党",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "214万円"
  },
  {
    "name": "小松 久子",
    "age": "72",
    "party": "東京・生活者ネットワーク",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "金 まさのり",
    "age": "70",
    "party": "無所属",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "佐々木 ちなつ",
    "age": "52",
    "party": "日本保守党（代表者：石濱哲信）",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "大谷 司郎",
    "age": "",
    "party": "日本保守党（代表者：百田尚樹）",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "吉田 博信",
    "age": "58",
    "party": "自治労と自治労連から国民を守る党",
    "recommendation": "",
    "district": "杉並区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "米倉 春奈",
    "age": "37",
    "party": "日本共産党",
    "recommendation": "",
    "district": "豊島区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "谷 きみよ",
    "age": "52",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "豊島区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "池田 ゆういち",
    "age": "48",
    "party": "自由民主党",
    "recommendation": "",
    "district": "豊島区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "中村 幸信",
    "age": "33",
    "party": "再生の道",
    "recommendation": "",
    "district": "豊島区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "本橋 ひろたか",
    "age": "63",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "豊島区",
    "proportional_rank": "",
    "relation": "2015年に豊島区議長として統一教会系「世界平和女性連合」の懇親会に参加し交際費から会費1.5万円を支出",
    "reference": "毎日新聞（東京面）2022年10月7日付「区議長交際費で支出 旧統一教会系へ 都副議長、15年に」（記者：望月衣塑子氏の報道より）",
    "secret_money": ""
  },
  {
    "name": "大松 あきら",
    "age": "64",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "北区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "きとう 直樹",
    "age": "41",
    "party": "日本維新の会",
    "recommendation": "",
    "district": "北区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "大場 宣夫",
    "age": "66",
    "party": "無所属",
    "recommendation": "",
    "district": "北区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "こまざき 美紀",
    "age": "46",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "北区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "戸枝 大幸",
    "age": "48",
    "party": "自由民主党",
    "recommendation": "",
    "district": "北区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "せいの 恵子",
    "age": "51",
    "party": "日本共産党",
    "recommendation": "",
    "district": "北区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "さいとう 和樹",
    "age": "42",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "荒川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "けいの 信一",
    "age": "49",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "荒川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "小林 ひろし",
    "age": "38",
    "party": "日本共産党",
    "recommendation": "",
    "district": "荒川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "町田 たかし",
    "age": "50",
    "party": "自由民主党",
    "recommendation": "",
    "district": "荒川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "南 貴大",
    "age": "37",
    "party": "再生の道",
    "recommendation": "",
    "district": "荒川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "山川 ゆうな",
    "age": "41",
    "party": "無所属",
    "recommendation": "",
    "district": "荒川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "かまた 悦子",
    "age": "52",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "津田 ふみや",
    "age": "27",
    "party": "日本維新の会",
    "recommendation": "",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "河野 ゆうき",
    "age": "55",
    "party": "自由民主党",
    "recommendation": "",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "39万円"
  },
  {
    "name": "宮瀬 英治",
    "age": "48",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "松田 やすまさ",
    "age": "48",
    "party": "自由民主党",
    "recommendation": "",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "船本 優月",
    "age": "33",
    "party": "再生の道",
    "recommendation": "",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "なかやま しづ",
    "age": "26",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "竹内 愛",
    "age": "48",
    "party": "日本共産党",
    "recommendation": "",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "高沢 一基",
    "age": "50",
    "party": "国民民主党",
    "recommendation": "",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "瀧口 修央",
    "age": "51",
    "party": "無所属",
    "recommendation": "",
    "district": "板橋区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "ふるやま 葉子",
    "age": "60",
    "party": "無所属",
    "recommendation": "東京・生活者ネットワーク",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "小川 けいこ",
    "age": "57",
    "party": "無所属",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "江崎 さなえ",
    "age": "39",
    "party": "参政党",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "村松 一希",
    "age": "44",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "やまか あけみ",
    "age": "71",
    "party": "自由民主党",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "統一教会関連団体の会合に「出席したことがある」と都のアンケートで回答",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": ""
  },
  {
    "name": "小林 けんじ",
    "age": "55",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "とや 英津子",
    "age": "61",
    "party": "日本共産党",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "山口 花",
    "age": "28",
    "party": "国民民主党",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "わかたび 啓太",
    "age": "35",
    "party": "日本維新の会",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "うえま あつこ",
    "age": "49",
    "party": "再生の道",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "なべおか 幸則",
    "age": "43",
    "party": "練馬未来の党",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "おじま 紘平",
    "age": "36",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "しばざき 幹男",
    "age": "69",
    "party": "自由民主党",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "統一教会側から「選挙支援を受けた」ほか関連団体の会合に「出席したことがある」と都のアンケートに回答",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": "241万円"
  },
  {
    "name": "藤井 とものり",
    "age": "49",
    "party": "立憲民主党",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "たぐち ゆり",
    "age": "43",
    "party": "れいわ新選組",
    "recommendation": "",
    "district": "練馬区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "うすい 浩一",
    "age": "65",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "榎本 二実子",
    "age": "48",
    "party": "自由民主党",
    "recommendation": "",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "えら やすひろ",
    "age": "31",
    "party": "再生の道",
    "recommendation": "",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "片岡 ひろし",
    "age": "66",
    "party": "再生の道",
    "recommendation": "",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "大竹 さよこ",
    "age": "55",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "斉藤 まりこ",
    "age": "50",
    "party": "日本共産党",
    "recommendation": "",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "くすみ 勇樹",
    "age": "41",
    "party": "無所属",
    "recommendation": "国民民主党",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "ほっち 易隆",
    "age": "49",
    "party": "自由民主党",
    "recommendation": "",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "37万円"
  },
  {
    "name": "後藤 なみ",
    "age": "38",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "銀川 ゆい子",
    "age": "39",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "金原 ともや",
    "age": "25",
    "party": "自治労と自治労連から国民を守る党",
    "recommendation": "",
    "district": "足立区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "北口 つよし",
    "age": "50",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "葛飾区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "岩見 なつよ",
    "age": "56",
    "party": "再生の道",
    "recommendation": "",
    "district": "葛飾区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "黒田 こうへい",
    "age": "37",
    "party": "無所属",
    "recommendation": "",
    "district": "葛飾区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "ときざき 直行",
    "age": "35",
    "party": "国民民主党",
    "recommendation": "",
    "district": "葛飾区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "和泉 なおみ",
    "age": "63",
    "party": "日本共産党",
    "recommendation": "",
    "district": "葛飾区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "米川 大二郎",
    "age": "57",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "葛飾区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "平田 みつよし",
    "age": "51",
    "party": "自由民主党",
    "recommendation": "",
    "district": "葛飾区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "小川 ゆうた",
    "age": "34",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "葛飾区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "上田 令子",
    "age": "60",
    "party": "無所属",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "竹平 ちはる",
    "age": "59",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "天沼 ひろし",
    "age": "63",
    "party": "国民民主党",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "福岡 なつみ",
    "age": "57",
    "party": "再生の道",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "村上 さやか",
    "age": "41",
    "party": "日本維新の会",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "山田 あさみ",
    "age": "44",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "田の上 いくこ",
    "age": "55",
    "party": "無所属",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "2010年頃から旧統一教会の関連団体である世界平和女性連合と接触があり、2015年・2021年・2022年に同団体の講演会や集会に計3回参加し、参加費を支払っていたことを自身の公式サイトで公表しています",
    "reference": "自身のHP",
    "secret_money": ""
  },
  {
    "name": "宇田川 さとし",
    "age": "60",
    "party": "無所属",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "統一教会関連団体の会合に「出席したことがある」と都のアンケートに回答",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": "138万円"
  },
  {
    "name": "原 純子",
    "age": "60",
    "party": "日本共産党",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "ふなはし ゆめと",
    "age": "59",
    "party": "自治労と自治労連から国民を守る党",
    "recommendation": "",
    "district": "江戸川区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "東村 くにひろ",
    "age": "63",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "馬場 たかひろ",
    "age": "46",
    "party": "自由民主党",
    "recommendation": "",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "滝田 やすひこ",
    "age": "43",
    "party": "無所属",
    "recommendation": "",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "すなみ 薫",
    "age": "63",
    "party": "再生の道",
    "recommendation": "",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "有希子",
    "age": "46",
    "party": "日本共産党",
    "recommendation": "",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "伊藤 しょうこう",
    "age": "56",
    "party": "自由民主党",
    "recommendation": "",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "旧統一教会側からの献金やパーティー券購入を受けたこと、選挙応援を受けたこと、そして関連団体の会合に出席したことがあると、東京都のアンケートで明らかにしました。",
    "reference": "日テレNEWS「“統一教会”メディア批判『法的手段』も…萩生田氏また新証言『弁論大会』にも出席か」（2022年8月22日）",
    "secret_money": "194万円"
  },
  {
    "name": "須山 たかし",
    "age": "44",
    "party": "無所属",
    "recommendation": "国民民主党",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "よくら さゆり",
    "age": "41",
    "party": "参政党",
    "recommendation": "",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "両角 みのる",
    "age": "63",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "細貝 悠",
    "age": "32",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "伊藤 あゆみ",
    "age": "54",
    "party": "無所属",
    "recommendation": "",
    "district": "八王子市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "伊藤 大輔",
    "age": "50",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "立川市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "やた 一久",
    "age": "34",
    "party": "無所属",
    "recommendation": "",
    "district": "立川市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "鈴木 烈",
    "age": "51",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "立川市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "川口 めぐみ",
    "age": "59",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "立川市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "東 まり子",
    "age": "59",
    "party": "自由民主党",
    "recommendation": "",
    "district": "武蔵野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "松井 たかお",
    "age": "50",
    "party": "国民民主党",
    "recommendation": "",
    "district": "武蔵野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "笹岡 ゆうこ",
    "age": "39",
    "party": "無所属",
    "recommendation": "東京・生活者ネットワーク",
    "district": "武蔵野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "尾花山 かずや",
    "age": "42",
    "party": "再生の道",
    "recommendation": "",
    "district": "武蔵野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "林 英明",
    "age": "30",
    "party": "無所属",
    "recommendation": "",
    "district": "三鷹市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "かめおか さやか",
    "age": "46",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "三鷹市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "山田 ひろし",
    "age": "40",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "三鷹市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "中村 ひろし",
    "age": "53",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "三鷹市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "中村 まなみ",
    "age": "55",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "青梅市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "兵頭 秀一",
    "age": "60",
    "party": "無所属",
    "recommendation": "",
    "district": "青梅市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "森村 たかゆき",
    "age": "51",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "青梅市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "小山 くにひこ",
    "age": "49",
    "party": "無所属",
    "recommendation": "",
    "district": "府中市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "増山 あすか",
    "age": "47",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "府中市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "村越 じゅんた",
    "age": "42",
    "party": "再生の道",
    "recommendation": "",
    "district": "府中市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "岸 慎一郎",
    "age": "57",
    "party": "日本共産党",
    "recommendation": "",
    "district": "府中市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "作本 純子",
    "age": "51",
    "party": "無所属",
    "recommendation": "",
    "district": "府中市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "内山 真吾",
    "age": "45",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "昭島市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "松尾 まさひろ",
    "age": "36",
    "party": "再生の道",
    "recommendation": "",
    "district": "昭島市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "安保 みつる",
    "age": "63",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "昭島市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "山花 のり子",
    "age": "67",
    "party": "無所属",
    "recommendation": "日本共産党",
    "district": "昭島市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "広田 ゆう大",
    "age": "30",
    "party": "国民民主党",
    "recommendation": "",
    "district": "町田市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "村松 としたか",
    "age": "47",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "町田市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "たきぐち 昭彦",
    "age": "64",
    "party": "再生の道",
    "recommendation": "",
    "district": "町田市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "東 友美",
    "age": "41",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "町田市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "浅井 なおゆき",
    "age": "61",
    "party": "再生の道",
    "recommendation": "",
    "district": "町田市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "藤井 あきら",
    "age": "43",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "町田市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "星 だいすけ",
    "age": "44",
    "party": "自由民主党",
    "recommendation": "",
    "district": "町田市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "12万円"
  },
  {
    "name": "池川 友一",
    "age": "40",
    "party": "日本共産党",
    "recommendation": "",
    "district": "町田市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "漢人 あきこ",
    "age": "65",
    "party": "無所属",
    "recommendation": "日本共産党/東京・生活者ネットワーク",
    "district": "小金井市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "すけだ 雄也",
    "age": "40",
    "party": "再生の道",
    "recommendation": "",
    "district": "小金井市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "大澤 つとむ",
    "age": "64",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "小金井市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "堀口 ひなこ",
    "age": "36",
    "party": "国民民主党",
    "recommendation": "",
    "district": "小金井市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "松岡 あつし",
    "age": "40",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "小平市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "竹井 ようこ",
    "age": "59",
    "party": "立憲民主党",
    "recommendation": "東京・生活者ネットワーク",
    "district": "小平市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "磯山 りょう",
    "age": "45",
    "party": "自由民主党",
    "recommendation": "",
    "district": "小平市",
    "proportional_rank": "",
    "relation": "2021年8月に統一教会系イベント「Peace Road 2021」の来賓挨拶に出席（支援者の依頼で参加）",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": ""
  },
  {
    "name": "大塚 きいち",
    "age": "49",
    "party": "再生の道",
    "recommendation": "",
    "district": "小平市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "西野 正人",
    "age": "65",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "日野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "寺前 ももこ",
    "age": "37",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "日野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "清水 とし子",
    "age": "62",
    "party": "日本共産党",
    "recommendation": "",
    "district": "日野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "石田 ゆたか",
    "age": "59",
    "party": "再生の道",
    "recommendation": "",
    "district": "日野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "池田 としえ",
    "age": "66",
    "party": "無所属",
    "recommendation": "",
    "district": "日野市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "浜中 のりかた",
    "age": "42",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "西東京市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "戸村 あんみ",
    "age": "34",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "西東京市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "桐山 ひとみ",
    "age": "54",
    "party": "無所属",
    "recommendation": "東京・生活者ネットワーク",
    "district": "西東京市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "河添 ひろし",
    "age": "50",
    "party": "再生の道",
    "recommendation": "",
    "district": "西東京市",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "清水 やすこ",
    "age": "58",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "西多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "田村 利光",
    "age": "58",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "西多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "287万円"
  },
  {
    "name": "奥泉 あきひろ",
    "age": "56",
    "party": "再生の道",
    "recommendation": "",
    "district": "西多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "梶原 元",
    "age": "38",
    "party": "自治労と自治労連から国民を守る党",
    "recommendation": "",
    "district": "西多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "渡辺 純平",
    "age": "40",
    "party": "再生の道",
    "recommendation": "",
    "district": "南多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "遠藤 ちひろ",
    "age": "49",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "南多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "こいそ 明",
    "age": "73",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "南多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "岩佐 ゆきひろ",
    "age": "43",
    "party": "無所属",
    "recommendation": "",
    "district": "南多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "藤原",
    "age": "66",
    "party": "無所属",
    "recommendation": "",
    "district": "南多摩",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "高田 きよひさ",
    "age": "49",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "北多摩第一",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "関野 たかなり",
    "age": "51",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "北多摩第一",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "土方 かつら",
    "age": "55",
    "party": "自由民主党",
    "recommendation": "",
    "district": "北多摩第一",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "尾崎 あや子",
    "age": "66",
    "party": "日本共産党",
    "recommendation": "",
    "district": "北多摩第一",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "石井 まさき",
    "age": "64",
    "party": "再生の道",
    "recommendation": "",
    "district": "北多摩第一",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "本橋 たくみ",
    "age": "42",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "北多摩第二",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "10万円"
  },
  {
    "name": "井上 あいり",
    "age": "32",
    "party": "国民民主党",
    "recommendation": "",
    "district": "北多摩第二",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "土田 ひろし",
    "age": "55",
    "party": "再生の道",
    "recommendation": "",
    "district": "北多摩第二",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "岩永 やす代",
    "age": "53",
    "party": "東京・生活者ネットワーク",
    "recommendation": "",
    "district": "北多摩第二",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "いいだ 健一",
    "age": "41",
    "party": "公明党",
    "recommendation": "自由民主党",
    "district": "北多摩第三",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "尾崎 大介",
    "age": "51",
    "party": "都民ファーストの会",
    "recommendation": "",
    "district": "北多摩第三",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "こうぐち 信明",
    "age": "55",
    "party": "再生の道",
    "recommendation": "",
    "district": "北多摩第三",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "林 あきひろ",
    "age": "64",
    "party": "自由民主党",
    "recommendation": "",
    "district": "北多摩第三",
    "proportional_rank": "",
    "relation": "統一教会側から「選挙支援を受けた」ほか関連団体の会合に「出席したことがある」と都のアンケートで回答",
    "reference": "共同通信「旧統一教会と政治の関係 都道府県議員アンケート 東京都」※都議へのアンケート結果（2022年実施）",
    "secret_money": ""
  },
  {
    "name": "田中 とも子",
    "age": "67",
    "party": "日本共産党",
    "recommendation": "",
    "district": "北多摩第三",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "細谷 しょうこ",
    "age": "71",
    "party": "国民民主党",
    "recommendation": "",
    "district": "北多摩第四",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "渋谷 のぶゆき",
    "age": "56",
    "party": "自由民主党",
    "recommendation": "公明党",
    "district": "北多摩第四",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "仲 れいこ",
    "age": "36",
    "party": "再生の道",
    "recommendation": "",
    "district": "北多摩第四",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "原 のり子",
    "age": "59",
    "party": "日本共産党",
    "recommendation": "",
    "district": "北多摩第四",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "奥村 こうき",
    "age": "25",
    "party": "再生の道",
    "recommendation": "",
    "district": "島部",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "伊藤 しょう",
    "age": "34",
    "party": "国民民主党",
    "recommendation": "",
    "district": "島部",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "三宅 正彦",
    "age": "53",
    "party": "無所属",
    "recommendation": "公明党",
    "district": "島部",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": "332万円"
  },
  {
    "name": "佐藤 沙織里",
    "age": "35",
    "party": "無所属",
    "recommendation": "",
    "district": "千代田区",
    "proportional_rank": "",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "山田 太郎",
    "age": "",
    "party": "自由民主党",
    "recommendation": "",
    "district": "比例",
    "proportional_rank": "1",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "佐藤 花子",
    "age": "",
    "party": "自由民主党",
    "recommendation": "",
    "district": "比例",
    "proportional_rank": "2",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "鈴木 一郎",
    "age": "",
    "party": "日本共産党",
    "recommendation": "",
    "district": "比例",
    "proportional_rank": "1",
    "relation": "",
    "reference": "",
    "secret_money": ""
  },
  {
    "name": "高橋 玲子",
    "age": "",
    "party": "日本共産党",
    "recommendation": "",
    "district": "比例",
    "proportional_rank": "2",
    "relation": "",
    "reference": "",
    "secret_money": ""
  }
];
